### ISSUE TITLE
No wayland and direct to display support on Linux

### ISSUE THREAD

**Issue by Unesty** [SingularityAzure/AzCore#1]
They are faster and more modern than Xorg

**Comment by Equivocatorrr** [comment]
Wayland support is planned for when it becomes more widespread. As it stands right now, none of my machines run Wayland, and AFAIK X11 programs can run on Wayland, so I'm not in a big hurry on that.

Direct to display is something I'll have to look into, but it sounds like a good next step.

**Comment by Equivocatorrr** [comment]
Testing branch has an implementation of Wayland support. A little more testing is needed before it's merged into main, but it's pretty much all there.
